# Generated by Django 3.2.7 on 2021-09-07 08:07

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first', models.CharField(max_length=50)),
                ('last', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email')),
                ('password', models.CharField(default='NullPassword', max_length=1000)),
                ('cin', models.CharField(max_length=8)),
                ('date_Birth', models.DateField()),
                ('role', models.CharField(choices=[('assistant', 'assistant'), ('doctor', 'doctor'), ('patient', 'patient')], default='patient', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Respiratoire_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rales_sibilants', models.BooleanField()),
                ('ralents_ronflants', models.CharField(max_length=200)),
                ('pleuresie', models.CharField(choices=[('Dplus', 'Dplus'), ('G', 'G'), ('B', 'B')], max_length=10)),
                ('pneumothorax', models.CharField(choices=[('D', 'D'), ('G', 'G'), ('B', 'B')], max_length=10)),
                ('crépitauts', models.BooleanField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Respiratoire_Exams', to='CabinetApp.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Radilogical_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thorax', models.CharField(max_length=200)),
                ('rx_standard', models.CharField(max_length=200)),
                ('tdm', models.CharField(max_length=200)),
                ('irm', models.CharField(max_length=200)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Radilogical_Exams', to='CabinetApp.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.IntegerField()),
                ('url_img', models.CharField(max_length=40)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Neurologique_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal', models.BooleanField()),
                ('vertige', models.BooleanField()),
                ('autre', models.CharField(max_length=200)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Neurologique_Exams', to='CabinetApp.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anti_biotique', models.CharField(max_length=200)),
                ('anti_inflammatoire', models.CharField(max_length=200)),
                ('antalgique', models.CharField(max_length=200)),
                ('anti_spasmodique', models.CharField(max_length=200)),
                ('ipp', models.CharField(max_length=200)),
                ('anti_émétique', models.CharField(max_length=200)),
                ('anti_diarrhéique', models.CharField(max_length=200)),
                ('laxatif', models.CharField(max_length=200)),
                ('charbon_activé', models.CharField(max_length=200)),
                ('anti_histaminique', models.CharField(max_length=200)),
                ('corticotde', models.CharField(max_length=200)),
                ('anti_hta', models.CharField(max_length=200)),
                ('b_bloquant', models.CharField(max_length=200)),
                ('anti_cholestérolémique', models.CharField(max_length=200)),
                ('ado', models.CharField(max_length=200)),
                ('insuline', models.CharField(max_length=200)),
                ('levothyrox', models.CharField(max_length=200)),
                ('dimazol', models.CharField(max_length=200)),
                ('magnesium', models.CharField(max_length=200)),
                ('auxiolytique', models.CharField(max_length=200)),
                ('anti_depresseur', models.CharField(max_length=200)),
                ('vitamine', models.CharField(max_length=200)),
                ('anti_mucosique', models.CharField(max_length=200)),
                ('ctc_local', models.CharField(max_length=200)),
                ('autres', models.CharField(max_length=200)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='CabinetApp.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='General_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta', models.CharField(max_length=200)),
                ('fc', models.CharField(max_length=200)),
                ('fr', models.CharField(max_length=200)),
                ('t', models.CharField(max_length=200)),
                ('poids', models.CharField(max_length=200)),
                ('taille', models.CharField(max_length=200)),
                ('conjonctive', models.CharField(choices=[('normocolorées', 'normocolorées'), ('décolorées', 'décolorées'), ('ictériques', 'ictériques')], max_length=20)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='General_Exams', to='CabinetApp.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_Folder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='CabinetApp.folder'),
        ),
        migrations.CreateModel(
            name='Cardio_vasculaire_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rythme', models.CharField(choices=[('régulier', 'régulier'), ('irrégulier', 'irrégulier')], max_length=10)),
                ('retricissement', models.CharField(choices=[('M', 'M'), ('T', 'T'), ('A', 'A'), ('P', 'P')], max_length=10)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cardio_vasculaire_Exams', to='CabinetApp.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Biological_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaj', models.CharField(max_length=200)),
                ('hba1c', models.CharField(max_length=200)),
                ('urée', models.CharField(max_length=200)),
                ('creat', models.CharField(max_length=200)),
                ('nfshb', models.CharField(max_length=200)),
                ('nfsgb', models.CharField(max_length=200)),
                ('nfspq', models.CharField(max_length=200)),
                ('férritinémie', models.CharField(max_length=200)),
                ('asat', models.CharField(max_length=200)),
                ('alat', models.CharField(max_length=200)),
                ('tsh', models.CharField(max_length=200)),
                ('ct', models.CharField(max_length=200)),
                ('tg', models.CharField(max_length=200)),
                ('ldl', models.CharField(max_length=200)),
                ('hdl', models.CharField(max_length=200)),
                ('ecbu', models.CharField(max_length=200)),
                ('vs', models.CharField(max_length=200)),
                ('crp', models.CharField(max_length=200)),
                ('autres', models.CharField(max_length=200)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Biological_Exams', to='CabinetApp.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=5)),
                ('status', models.IntegerField(default=0)),
                ('consultation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='CabinetApp.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Abdominal_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('douleur', models.CharField(choices=[('HD', 'HD'), ('HG', 'HG'), ('EPIG', 'EPIG'), ('FD', 'FD'), ('FG', 'FG'), ('O', 'O'), ('HYPAG', 'HYPAG')], max_length=10)),
                ('masse', models.CharField(choices=[('HD', 'HD'), ('HG', 'HG'), ('EPIG', 'EPIG'), ('FD', 'FD'), ('FG', 'FG'), ('O', 'O'), ('HYPAG', 'HYPAG')], max_length=10)),
                ('ascite', models.BooleanField()),
                ('tympanisme', models.BooleanField()),
                ('distension_tympanique', models.BooleanField()),
                ('hépatomégalie', models.BooleanField()),
                ('splénomégalie', models.BooleanField()),
                ('tr', models.CharField(max_length=200)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Abdominal_Exams', to='CabinetApp.consultation')),
            ],
        ),
    ]
